version: '3.4'
services:
  solvent:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - ./build:/opt/solvent/build
      - ./built:/opt/solvent/built
      - ./dist:/opt/solvent/dist
      - ./src:/opt/solvent/src
